import { NextResponse } from 'next/server';
import nodemailer from 'nodemailer';
import dns from 'dns/promises';
import { isFreeEmail, getEmailDomain } from '@/lib/email-validation';

// ── HTML email builder ────────────────────────────────────────────────────────

function field(label: string, value?: string) {
  if (!value) return '';
  return `
    <tr>
      <td style="padding:12px 0;border-bottom:1px solid rgba(255,255,255,0.06);">
        <p style="margin:0 0 4px;font-size:10px;text-transform:uppercase;letter-spacing:1.2px;color:rgba(255,250,243,0.35);font-family:'Helvetica Neue',sans-serif;">${label}</p>
        <p style="margin:0;font-size:15px;color:#FFFAF3;font-family:'Helvetica Neue',sans-serif;line-height:1.5;">${value}</p>
      </td>
    </tr>
  `;
}

function buildHtml(title: string, subtitle: string, rows: string) {
  const now = new Date().toLocaleString('en-US', {
    weekday: 'short', year: 'numeric', month: 'long', day: 'numeric',
    hour: '2-digit', minute: '2-digit', timeZoneName: 'short',
  });
  return `
<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/></head>
<body style="margin:0;padding:0;background:#0d0d0d;">
  <div style="max-width:560px;margin:0 auto;padding:32px 16px;">

    <!-- Header -->
    <div style="background:#141414;border-top:3px solid #FF6A1C;border-radius:12px 12px 0 0;padding:24px 32px;">
      <p style="margin:0 0 10px;font-size:14px;font-weight:700;color:#FF6A1C;letter-spacing:-0.3px;font-family:'Helvetica Neue',sans-serif;">NexivoStudio</p>
      <h1 style="margin:0 0 6px;font-size:22px;color:#FFFAF3;font-weight:600;font-family:'Helvetica Neue',sans-serif;">${title}</h1>
      <p style="margin:0;font-size:12px;color:rgba(255,250,243,0.35);font-family:'Helvetica Neue',sans-serif;">${subtitle}</p>
    </div>

    <!-- Divider -->
    <div style="height:1px;background:rgba(255,106,28,0.25);"></div>

    <!-- Body -->
    <div style="background:#141414;border-radius:0 0 12px 12px;padding:8px 32px 32px;">
      <table style="width:100%;border-collapse:collapse;">
        <tbody>
          ${rows}
          ${field('Received', now)}
        </tbody>
      </table>
    </div>

    <!-- Footer -->
    <p style="text-align:center;font-size:11px;color:rgba(255,250,243,0.2);margin-top:24px;font-family:'Helvetica Neue',sans-serif;">
      Automatically generated by the NexivoStudio website. Do not reply to this email.
    </p>
  </div>
</body>
</html>`;
}

// ── Route handler ─────────────────────────────────────────────────────────────

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { formType, name, email, phone, service, budget, message, plan, price, period, recaptchaToken } = body;

    // ── Email validation ─────────────────────────────────────────────────────
    if (!email || !/^\S+@\S+\.\S+$/.test(email)) {
      return NextResponse.json({ error: 'Invalid email address' }, { status: 400 });
    }

    if (isFreeEmail(email)) {
      return NextResponse.json(
        { error: 'Please use a company or business email address' },
        { status: 400 }
      );
    }

    // DNS MX record check — verify the email domain actually has mail servers
    try {
      const mx = await dns.resolveMx(getEmailDomain(email));
      if (!mx || mx.length === 0) {
        return NextResponse.json(
          { error: 'This email domain does not appear to exist' },
          { status: 400 }
        );
      }
    } catch {
      return NextResponse.json(
        { error: 'This email domain does not appear to exist' },
        { status: 400 }
      );
    }

    // ── reCAPTCHA Enterprise verification
    if (process.env.RECAPTCHA_API_KEY && process.env.RECAPTCHA_PROJECT_ID) {
      if (!recaptchaToken) {
        return NextResponse.json({ error: 'reCAPTCHA token missing' }, { status: 400 });
      }

      // Map form type to the expected action name (must match what the client sent)
      const actionMap: Record<string, string> = {
        'lead-form':       'lead_form',
        'contact':         'contact_form',
        'schedule-call':   'schedule_call',
        'pricing-inquiry': 'pricing_inquiry',
      };
      const expectedAction = actionMap[formType] ?? formType;

      const assessmentRes = await fetch(
        `https://recaptchaenterprise.googleapis.com/v1/projects/${process.env.RECAPTCHA_PROJECT_ID}/assessments?key=${process.env.RECAPTCHA_API_KEY}`,
        {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            event: {
              token: recaptchaToken,
              expectedAction,
              siteKey: process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY,
            },
          }),
        }
      );

      const assessment = await assessmentRes.json() as {
        tokenProperties?: { valid: boolean; action: string };
        riskAnalysis?: { score: number };
      };

      const valid = assessment.tokenProperties?.valid === true;
      const score = assessment.riskAnalysis?.score ?? 0;

      if (!valid || score < 0.5) {
        console.warn('[recaptcha] Blocked — valid:', valid, 'score:', score);
        return NextResponse.json({ error: 'reCAPTCHA verification failed' }, { status: 400 });
      }
    }

    if (!process.env.SMTP_HOST || !process.env.SMTP_USER || !process.env.SMTP_PASSWORD) {
      console.error('[contact] Missing SMTP credentials in .env.local');
      return NextResponse.json({ error: 'Email not configured' }, { status: 500 });
    }

    const transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST,
      port: Number(process.env.SMTP_PORT ?? 465),
      secure: process.env.SMTP_SECURE !== 'false',
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASSWORD,
      },
    });

    let subject = '';
    let html = '';

    if (formType === 'schedule-call') {
      subject = `📅 New Schedule-a-Call Request from ${name}`;
      html = buildHtml(
        'New Call Request',
        'Someone wants to schedule a call from the NexivoStudio website.',
        field('Full Name', name) +
        field('Email', email) +
        field('Phone', phone) +
        field('Service of Interest', service) +
        field('Project Budget', budget) +
        field('Project Details', message)
      );
    } else if (formType === 'lead-form') {
      subject = `🚀 New Consultation Request from ${name}`;
      html = buildHtml(
        'New Consultation Request',
        'Someone submitted the free consultation form on the homepage.',
        field('Full Name', name) +
        field('Email', email) +
        field('Phone', phone) +
        field('Service', service) +
        field('Message', message)
      );
    } else if (formType === 'contact') {
      subject = `💬 New Contact Message from ${name}`;
      html = buildHtml(
        'New Contact Message',
        'Someone sent a message via the Contact section.',
        field('Full Name', name) +
        field('Email', email) +
        field('Message', message)
      );
    } else if (formType === 'pricing-inquiry') {
      subject = `💰 Pricing Inquiry: ${plan} Plan (${service}) from ${name}`;
      html = buildHtml(
        'New Pricing Inquiry',
        `Someone is interested in the ${plan} plan for ${service}.`,
        field('Full Name', name) +
        field('Email', email) +
        field('Phone', phone) +
        field('Service', service) +
        field('Selected Plan', `${plan} — ${price}${period ? ` ${period}` : ''}`) +
        field('Notes', message)
      );
    } else {
      subject = `📩 New Website Inquiry from ${name ?? 'Unknown'}`;
      html = buildHtml(
        'New Website Inquiry',
        'A general inquiry was submitted on the NexivoStudio website.',
        field('Name', name) +
        field('Email', email) +
        field('Details', message)
      );
    }

    const fromName = process.env.FROM_NAME ?? 'NexivoStudio Website';
    const fromEmail = process.env.FROM_EMAIL ?? process.env.SMTP_USER;

    await transporter.sendMail({
      from: `"${fromName}" <${fromEmail}>`,
      to: process.env.TO_EMAIL ?? process.env.SMTP_USER,
      replyTo: email,
      subject,
      html,
    });

    return NextResponse.json({ success: true });
  } catch (err) {
    console.error('[contact] Failed to send email:', err);
    return NextResponse.json({ error: 'Failed to send' }, { status: 500 });
  }
}
