import type { NavLink, Service, Technology, PortfolioItem, BlogPost, ServiceCategory, ServicePricing } from '@/types';

export const NAV_LINKS: NavLink[] = [
  { label: 'Home',      href: '/'          },
  { label: 'About',     href: '/about'     },
  { label: 'Services',  href: '/services'  },
  { label: 'Pricing',   href: '/pricing'   },
  { label: 'Blog',      href: '/blog'      },
  { label: 'Portfolio', href: '/portfolio' },
  { label: 'Contact',   href: '/contact'   },
];

export const SERVICES: Service[] = [
  {
    icon: 'Palette',
    title: 'Web Design',
    description:
      'Stunning, user-centric designs that captivate your audience and drive conversions. We craft beautiful interfaces that tell your brand story.',
  },
  {
    icon: 'Code2',
    title: 'Web Development',
    description:
      'Scalable, performant web applications built with modern technologies. From landing pages to complex platforms — we code it right.',
  },
  {
    icon: 'Share2',
    title: 'Social Media Marketing',
    description:
      'Data-driven social strategies that grow your brand and engage your community. We create content that converts followers into customers.',
  },
  {
    icon: 'SearchCheck',
    title: 'SEO',
    description:
      'Comprehensive SEO solutions that increase your visibility and drive organic traffic. Outrank your competition with proven techniques.',
  },
];

export const SERVICE_CATEGORIES: ServiceCategory[] = [
  {
    icon: 'Palette',
    title: 'Web Design',
    slug: 'web-design',
    description: 'Stunning, user-centric designs that captivate your audience and drive conversions.',
    children: [
      { title: 'UI/UX Design', description: 'User-centered interface design with wireframes, prototypes, and high-fidelity mockups tailored to your brand.' },
      { title: 'Landing Page Design', description: 'High-converting, visually striking landing pages designed to turn visitors into leads.' },
      { title: 'E-Commerce Design', description: 'Product-focused store layouts designed for seamless browsing, trust, and conversion.' },
      { title: 'Brand Identity & Style Guides', description: 'Logo, color palette, typography, and component guidelines that keep your brand consistent everywhere.' },
      { title: 'Website Redesign', description: 'Modernize outdated websites with a fresh look while preserving SEO equity and user familiarity.' },
      { title: 'Mobile-First / Responsive Design', description: 'Designs built for every screen size — mobile, tablet, and desktop — from the ground up.' },
    ],
  },
  {
    icon: 'Code2',
    title: 'Web Development',
    slug: 'web-development',
    description: 'Scalable, performant web applications built with modern technologies.',
    children: [
      { title: 'Custom Website Development', description: 'Fully custom-built websites using modern frameworks — no bloated templates, just clean performant code.' },
      { title: 'WordPress Development', description: 'Custom themes, child themes, and plugin development for WordPress-based sites.' },
      { title: 'Next.js / React Development', description: 'Fast, SEO-friendly web applications built with Next.js and React for dynamic and static sites alike.' },
      { title: 'E-Commerce Development', description: 'Full WooCommerce or custom e-commerce builds with cart, checkout, payments, and order management.' },
      { title: 'Web Application Development', description: 'Complex web apps with authentication, dashboards, APIs, and database integrations.' },
      { title: 'API Integration', description: 'Connect your website to third-party services — CRMs, payment gateways, booking systems, and more.' },
      { title: 'Speed & Performance Optimization', description: 'Core Web Vitals tuning, image optimization, caching, and code splitting for blazing-fast load times.' },
      { title: 'Website Maintenance & Support', description: 'Ongoing updates, security patches, backups, and technical support to keep your site running smoothly.' },
    ],
  },
  {
    icon: 'Share2',
    title: 'Social Media Marketing',
    slug: 'social-media-marketing',
    description: 'Data-driven social strategies that grow your brand and engage your community.',
    children: [
      { title: 'Social Media Strategy', description: 'Platform-specific content strategies built around your audience, goals, and brand voice.' },
      { title: 'Content Creation & Design', description: 'Scroll-stopping graphics, reels, carousels, and copy crafted for each platform.' },
      { title: 'Social Media Management', description: 'Full-service account management — scheduling, posting, community engagement, and reporting.' },
      { title: 'Paid Social Advertising', description: 'ROI-focused ad campaigns on Meta (Facebook/Instagram), TikTok, LinkedIn, and more.' },
      { title: 'Influencer Marketing', description: 'Identifying, outreaching, and managing influencer partnerships aligned with your niche.' },
      { title: 'Analytics & Reporting', description: 'Monthly performance reports with insights on reach, engagement, follower growth, and conversions.' },
      { title: 'Profile Optimization', description: 'Bio, highlights, link-in-bio, and profile setup optimized for discoverability and first impressions.' },
    ],
  },
  {
    icon: 'SearchCheck',
    title: 'SEO',
    slug: 'seo',
    description: 'Comprehensive SEO solutions that increase your visibility and drive organic traffic.',
    children: [
      { title: 'SEO Audit', description: "A full technical and content audit identifying what's holding your site back in search rankings." },
      { title: 'On-Page SEO', description: 'Optimizing title tags, meta descriptions, headings, content, and internal linking structure.' },
      { title: 'Technical SEO', description: 'Site speed, crawlability, schema markup, sitemaps, robots.txt, and Core Web Vitals fixes.' },
      { title: 'Keyword Research & Strategy', description: 'Finding high-intent, low-competition keywords your audience is actually searching for.' },
      { title: 'Local SEO', description: 'Google Business Profile optimization, local citations, and geo-targeted content to dominate local search.' },
      { title: 'Link Building', description: 'White-hat outreach and digital PR to earn high-authority backlinks that boost domain authority.' },
      { title: 'E-Commerce SEO', description: 'Product page optimization, category structure, and schema for online stores.' },
      { title: 'SEO Content Writing', description: 'Blog posts, pillar pages, and landing page copy written to rank and convert.' },
    ],
  },
  {
    icon: 'Globe',
    title: 'Hosting & Domain',
    slug: 'hosting-domain',
    description: 'Reliable hosting and domain services to keep your website fast, secure, and always online.',
    children: [
      { title: 'Domain Registration', description: 'Search, register, and manage domain names across all major extensions (.com, .net, .org, and more).' },
      { title: 'Web Hosting', description: 'Shared, VPS, and dedicated hosting solutions tailored to your traffic and performance needs.' },
      { title: 'SSL Certificates', description: 'Secure your website and build visitor trust with industry-standard SSL/TLS encryption.' },
      { title: 'Email Hosting', description: 'Professional branded email accounts with spam filtering, large storage, and easy setup.' },
      { title: 'CDN Setup', description: 'Global content delivery network configuration for blazing-fast load times across every region.' },
      { title: 'Server Management', description: 'Full server setup, configuration, monitoring, and maintenance so you never have to worry about infrastructure.' },
    ],
  },
  {
    icon: 'Wrench',
    title: 'Website Maintenance',
    slug: 'website-maintenance',
    description: 'Ongoing support, updates, and monitoring to keep your website running at peak performance.',
    children: [
      { title: 'Content Updates', description: 'Regular text, image, and media updates to keep your website fresh and accurate.' },
      { title: 'Security Monitoring', description: 'Continuous malware scanning, vulnerability patching, and firewall management.' },
      { title: 'Plugin & CMS Updates', description: 'Keeping your WordPress plugins and third-party tools up to date and conflict-free.' },
      { title: 'Performance Optimization', description: 'Ongoing speed audits, caching tuning, and image optimization to maintain fast load times.' },
      { title: 'Backup & Recovery', description: 'Automated daily backups with one-click restore so your data is always protected.' },
      { title: 'Uptime Monitoring', description: '24/7 server and website uptime monitoring with instant alerts and rapid response.' },
      { title: 'Emergency Support', description: 'Priority bug fixes, crash recovery, and technical support when you need it most.' },
    ],
  },
];

export const TECHNOLOGIES: Technology[] = [
  { name: 'React', icon: 'react' },
  { name: 'Next.js', icon: 'nextjs' },
  { name: 'TypeScript', icon: 'typescript' },
  { name: 'Node.js', icon: 'nodejs' },
  { name: 'Tailwind CSS', icon: 'tailwind' },
  { name: 'Figma', icon: 'figma' },
  { name: 'WordPress', icon: 'wordpress' },
  { name: 'Shopify', icon: 'shopify' },
];

export const PORTFOLIO_TABS = ['All', 'Web Design', 'Web Dev', 'SEO', 'Social Media'] as const;
export type PortfolioTab = (typeof PORTFOLIO_TABS)[number];

export const PORTFOLIO_ITEMS: PortfolioItem[] = [
  {
    id: 1,
    title: 'Luxe Fashion Brand',
    category: 'Web Design',
    tag: 'UI/UX Design',
    image: 'from-purple-600 to-blue-500',
  },
  {
    id: 2,
    title: 'TechFlow Dashboard',
    category: 'Web Design',
    tag: 'Dashboard Design',
    image: 'from-orange-500 to-red-500',
  },
  {
    id: 3,
    title: 'E-Commerce Platform',
    category: 'Web Dev',
    tag: 'Full Stack',
    image: 'from-green-500 to-teal-400',
  },
  {
    id: 4,
    title: 'SaaS Landing Page',
    category: 'Web Dev',
    tag: 'Next.js',
    image: 'from-pink-500 to-purple-500',
  },
  {
    id: 5,
    title: 'Local Restaurant SEO',
    category: 'SEO',
    tag: 'Local SEO',
    image: 'from-yellow-400 to-orange-400',
  },
  {
    id: 6,
    title: 'Legal Firm Rankings',
    category: 'SEO',
    tag: 'Technical SEO',
    image: 'from-blue-400 to-indigo-500',
  },
  {
    id: 7,
    title: 'Fitness Brand Growth',
    category: 'Social Media',
    tag: 'Instagram Growth',
    image: 'from-red-500 to-pink-500',
  },
  {
    id: 8,
    title: 'Beauty Brand Campaign',
    category: 'Social Media',
    tag: 'Meta Ads',
    image: 'from-teal-400 to-cyan-500',
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 1,
    title: '10 Web Design Trends Dominating 2024',
    category: 'Web Design',
    excerpt:
      'Explore the cutting-edge design trends shaping the web in 2024, from glassmorphism to AI-generated visuals and beyond.',
    image: 'from-purple-600 to-indigo-500',
    date: 'Dec 15, 2024',
  },
  {
    id: 2,
    title: 'How to Skyrocket Your SEO Rankings in 90 Days',
    category: 'SEO',
    excerpt:
      'A proven step-by-step framework for dramatically improving your search rankings with technical and on-page SEO techniques.',
    image: 'from-green-500 to-emerald-400',
    date: 'Dec 10, 2024',
  },
  {
    id: 3,
    title: 'Social Media Strategies That Actually Convert',
    category: 'Social Media',
    excerpt:
      'Stop posting into the void. Learn the social media strategies that turn followers into paying customers and brand advocates.',
    image: 'from-orange-500 to-red-400',
    date: 'Dec 5, 2024',
  },
];

export const PRICING_PLANS: ServicePricing[] = [
  {
    service: 'Web Design',
    slug: 'web-design',
    plans: [
      {
        name: 'Starter',
        price: '$499',
        description: 'Perfect for small businesses needing a professional online presence.',
        features: [
          'Landing page design (1 page)',
          'UI/UX wireframes',
          'Figma source files',
          '1 revision round',
          'Mobile-responsive design',
          '7-day delivery',
        ],
        cta: 'Get Started',
      },
      {
        name: 'Pro',
        price: '$1,299',
        description: 'Full website design for growing brands that want to stand out.',
        features: [
          'Up to 8 page designs',
          'Full UI/UX design system',
          'Brand style guide included',
          '3 revision rounds',
          'Mobile-first & responsive',
          'Interactive Figma prototype',
          '14-day delivery',
        ],
        highlighted: true,
        cta: 'Get Started',
      },
      {
        name: 'Agency',
        price: '$2,499',
        description: 'Enterprise-grade design for complex websites and digital products.',
        features: [
          'Unlimited page designs',
          'Complete brand identity kit',
          'UI component library',
          'Unlimited revisions',
          'Custom animations & interactions',
          'Priority designer access',
          'Dedicated project manager',
        ],
        cta: 'Contact Us',
      },
    ],
  },
  {
    service: 'Web Development',
    slug: 'web-development',
    plans: [
      {
        name: 'Starter',
        price: '$699',
        description: 'A clean, fast website to establish your digital footprint.',
        features: [
          'Up to 5 pages',
          'Fully responsive build',
          'Basic contact form',
          'Google Analytics setup',
          'On-page SEO basics',
          '14-day support',
        ],
        cta: 'Get Started',
      },
      {
        name: 'Pro',
        price: '$1,799',
        description: 'A powerful site with CMS, animations & integrations.',
        features: [
          'Up to 10 pages',
          'CMS integration (WordPress / Next.js)',
          'Custom animations (GSAP)',
          'Third-party API integrations',
          'Performance optimization',
          'Full SEO setup',
          '30-day support',
        ],
        highlighted: true,
        cta: 'Get Started',
      },
      {
        name: 'Agency',
        price: '$3,999',
        description: 'Full-scale web applications and e-commerce platforms.',
        features: [
          'Unlimited pages',
          'Custom web app / e-commerce',
          'Authentication & dashboards',
          'Payment gateway integration',
          'Advanced API & database work',
          'Core Web Vitals optimization',
          '60-day support',
          'Dedicated developer',
        ],
        cta: 'Contact Us',
      },
    ],
  },
  {
    service: 'Social Media Marketing',
    slug: 'social-media-marketing',
    plans: [
      {
        name: 'Starter',
        price: '$299',
        period: '/mo',
        description: 'Get started growing your brand on social media.',
        features: [
          '2 social media platforms',
          '12 posts per month',
          'Basic content design',
          'Caption & hashtag strategy',
          'Monthly performance report',
        ],
        cta: 'Get Started',
      },
      {
        name: 'Pro',
        price: '$699',
        period: '/mo',
        description: 'Accelerate growth with ads, reels & deep engagement.',
        features: [
          '4 social media platforms',
          '24 posts per month',
          'Custom graphics + Reels / TikToks',
          'Paid social ad management',
          'Community engagement & replies',
          'Bi-weekly performance reports',
        ],
        highlighted: true,
        cta: 'Get Started',
      },
      {
        name: 'Agency',
        price: '$1,299',
        period: '/mo',
        description: 'Full-service social media management for serious brands.',
        features: [
          'All social platforms',
          'Daily posting schedule',
          'Full content production',
          'Influencer outreach & management',
          'Advanced paid ad campaigns',
          'Dedicated account manager',
          'Weekly reporting & strategy calls',
        ],
        cta: 'Contact Us',
      },
    ],
  },
  {
    service: 'SEO',
    slug: 'seo',
    plans: [
      {
        name: 'Starter',
        price: '$399',
        period: '/mo',
        description: 'Build your search foundation with core SEO essentials.',
        features: [
          'Full SEO audit',
          'On-page optimization (up to 10 pages)',
          'Keyword research & strategy',
          'Google Search Console setup',
          'Monthly ranking report',
        ],
        cta: 'Get Started',
      },
      {
        name: 'Pro',
        price: '$799',
        period: '/mo',
        description: 'Aggressive SEO strategy with content & link building.',
        features: [
          'On-page + technical SEO',
          'Up to 25 pages optimized',
          '5 SEO blog posts per month',
          'Link building outreach',
          'Local SEO optimization',
          'Bi-weekly ranking reports',
        ],
        highlighted: true,
        cta: 'Get Started',
      },
      {
        name: 'Agency',
        price: '$1,499',
        period: '/mo',
        description: 'Dominate search results with enterprise-level SEO.',
        features: [
          'Unlimited page optimization',
          'Full technical SEO overhaul',
          '10+ SEO blog posts per month',
          'E-commerce SEO',
          'Advanced link building',
          'Schema & structured data',
          'Dedicated SEO strategist',
          'Weekly reporting & calls',
        ],
        cta: 'Contact Us',
      },
    ],
  },
  {
    service: 'Hosting & Domain',
    slug: 'hosting-domain',
    plans: [
      {
        name: 'Starter',
        price: '$9.99',
        period: '/mo',
        description: 'Everything you need to get online fast and stay there.',
        features: [
          'Domain registration (1 year)',
          'Shared hosting',
          'Free SSL certificate',
          '5 GB SSD storage',
          '1 branded email address',
          '99.9% uptime guarantee',
        ],
        cta: 'Get Started',
      },
      {
        name: 'Pro',
        price: '$29.99',
        period: '/mo',
        description: 'More power, speed, and flexibility for growing websites.',
        features: [
          '2 domain registrations',
          'Premium cloud hosting',
          'Free SSL + auto-renewal',
          '50 GB SSD storage',
          '10 branded email addresses',
          'Daily automated backups',
          'CDN included',
        ],
        highlighted: true,
        cta: 'Get Started',
      },
      {
        name: 'Agency',
        price: '$79.99',
        period: '/mo',
        description: 'High-performance VPS for demanding sites and agencies.',
        features: [
          'Unlimited domains',
          'VPS / dedicated hosting',
          'Advanced firewall & DDoS protection',
          '500 GB NVMe storage',
          'Unlimited email accounts',
          'Advanced CDN & caching',
          'Managed server updates',
          'Priority 24/7 support',
        ],
        cta: 'Contact Us',
      },
    ],
  },
  {
    service: 'Website Maintenance',
    slug: 'website-maintenance',
    plans: [
      {
        name: 'Starter',
        price: '$99',
        period: '/mo',
        description: 'Essential care to keep your website healthy and up to date.',
        features: [
          'Up to 3 content updates/mo',
          'Security monitoring',
          'Plugin & CMS updates',
          'Monthly backup',
          'Monthly performance report',
        ],
        cta: 'Get Started',
      },
      {
        name: 'Pro',
        price: '$249',
        period: '/mo',
        description: 'Proactive maintenance with performance tuning and priority support.',
        features: [
          'Up to 10 content updates/mo',
          'Advanced security scanning',
          'Speed & Core Web Vitals tuning',
          'Weekly backups',
          'Uptime monitoring',
          'Priority support',
          'Bi-weekly performance reports',
        ],
        highlighted: true,
        cta: 'Get Started',
      },
      {
        name: 'Agency',
        price: '$499',
        period: '/mo',
        description: 'Unlimited support with a dedicated tech team on your side.',
        features: [
          'Unlimited content updates',
          '24/7 uptime & security monitoring',
          'Emergency bug fix support',
          'Daily automated backups',
          'Full technical support',
          'Dedicated account manager',
          'Weekly reporting & strategy calls',
        ],
        cta: 'Contact Us',
      },
    ],
  },
];
